version: '3.5'

services:
  database:
    build: ./database
    environment:
      TZ: Europe/Paris
      PGDATA: /data/postgres
    volumes:
       - jareth_database:/data/postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db.dev
  
  webservice:
    build: ./webservice
    environment:
      TZ: Europe/Paris
    command: flask run -h 0.0.0.0 
    volumes:
      - ./webservice/:/usr/src/app/
    ports:
      - 42001:5000
    env_file:
      - ./.env.ws.dev
    depends_on:
      - database
      
#  front:
#    build: ./front
#    environment:
#      TZ: Europe/Paris
#    command: flask run -h 0.0.0.0 
#    volumes:
#      - ./front/:/usr/src/app/
#    ports:
#      - 42002:5000
#    env_file:
#      - ./.env.front.dev
#    depends_on:
#      - webservice
          
volumes:
  jareth_database:
